services:
  flume:
    image: bde2020/flume
    container_name: agente_flume
    volumes:
      - ./:/workspace
    command: /app/bin/flume-ng agent -n a1 -c /app/conf -f /workspace/flume/flume-ecommerce.conf -Dflume.root.logger=INFO,console

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: projeto_bigdata_namenode
    environment:
      - CLUSTER_NAME=ecommerce
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9871:9870"
      - "9001:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: projeto_bigdata_datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - namenode
    volumes:
      - datanode_data:/hadoop/dfs/data

volumes:
  namenode_data:
  datanode_data: