# 1. O nosso agente será chamado de a1
a1.sources = r1
a1.channels = c1
a1.sinks = k1

# 2. Configurando o SOURCE (A entrada - O nosso Vigia)
a1.sources.r1.type = TAILDIR

# Nomeamos o grupo de arquivos que ele vai vigiar como "f1"
a1.sources.r1.filegroups = f1
# ATENÇÃO: Este é o caminho dentro do container do Flume. 
a1.sources.r1.filegroups.f1 = /workspace/dados/eventos.json

# 3. Configurando o CHANNEL (O meio de campo)
# Usaremos a memória RAM, que é super rápida para testes
a1.channels.c1.type = memory
a1.channels.c1.capacity = 10000
a1.channels.c1.transactionCapacity = 1000

# 4. Configurando o SINK (A saída)
# O tipo "logger" apenas imprime os dados no terminal para provar que a captura funcionou.
a1.sinks.k1.type = logger

# 5. Ligando as peças (Conectando as mangueiras)
a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1