a1.sources = r1
a1.channels = c1
a1.sinks = k1

# SOURCE
a1.sources.r1.type = TAILDIR
a1.sources.r1.filegroups = f1
a1.sources.r1.filegroups.f1 = /workspace/dados/eventos.json

# CHANNEL
a1.channels.c1.type = memory
a1.channels.c1.capacity = 10000
a1.channels.c1.transactionCapacity = 1000

# SINK HDFS
a1.sinks.k1.type = hdfs
a1.sinks.k1.hdfs.path = hdfs://namenode:9000/ecommerce/raw
a1.sinks.k1.hdfs.filePrefix = eventos-
a1.sinks.k1.hdfs.fileSuffix = .json
a1.sinks.k1.hdfs.inUsePrefix = _
a1.sinks.k1.hdfs.fileType = DataStream
a1.sinks.k1.hdfs.writeFormat = Text
a1.sinks.k1.hdfs.rollInterval = 10
a1.sinks.k1.hdfs.rollSize = 0
a1.sinks.k1.hdfs.rollCount = 0

# LIGAÇÕES
a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1